// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"fr": &dictionary{index: frIndex, data: frData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	" (default %q)":        39,
	" (default %s)":        38,
	"%s:":                  36,
	"ADDITIONNAL HELP":     44,
	"ALIASES":              41,
	"Additional Commands:": 37,
	"An error occured calculating an absolute path: %s":   9,
	"An error occured when checking the path \"%s\":\n%s": 10,
	"Boost your development workflow by at least 10^12.":  1,
	"COMMANDS": 43,
	"Display help information about the command": 2,
	"Display version information":                3,
	"ERROR":                                      33,
	"EXAMPLE":                                    42,
	"Failed to read the current working directory: %s":       12,
	"No command is declared":                                 25,
	"No configuration file could be found":                   13,
	"No job and no service is declared in the configuration": 26,
	"No name is declared":                                    22,
	"No step is declared in the job \"%s\"":                  15,
	"No valid configuration could be found":                  31,
	"Path to a configuration file. If left empty, it will recursively search in the parent directories for a .tera.yml file": 7,
	"Print version and exit":                                              4,
	"Run a job":                                                           6,
	"Start the service management interface":                              8,
	"The configuration is invalid: %s":                                    30,
	"The contents of the file \"%s\" could not be read: %s":               32,
	"The file could not be parsed from YAML: %s":                          29,
	"The key of a service is not defined":                                 27,
	"The path \"%s\" is a directory":                                      11,
	"The run_after hooks are invalid: %s":                                 24,
	"The run_before hooks are invalid: %s":                                23,
	"The service \"%s\" is invalid: %s":                                   28,
	"The step \"%s\" in the job \"%s\" has invalid run_after hooks: %s":   18,
	"The step \"%s\" in the job \"%s\" has invalid run_before hooks: %s":  17,
	"The step \"%s\" in the job \"%s\" has no task declared":              19,
	"The step #%d in the job \"%s\" has no name declared":                 16,
	"The task \"%s\" in the step \"%s\" in the job \"%s\" is invalid: %s": 20,
	"The task #%d has no command declared":                                14,
	"The task #%d in the step \"%s\" in the job \"%s\" is invalid: %s":    21,
	"USAGE":                       40,
	"[--flags]":                   35,
	"[command]":                   34,
	"tera version %s\n":           5,
	"unknown (built from source)": 0,
}

var enIndex = []uint32{ // 46 elements
	// Entry 0 - 1F
	0x00000000, 0x0000001c, 0x0000004f, 0x0000007a,
	0x00000096, 0x000000ad, 0x000000c5, 0x000000cf,
	0x00000146, 0x0000016d, 0x000001a2, 0x000001d9,
	0x000001f9, 0x0000022d, 0x00000252, 0x0000027a,
	0x000002a1, 0x000002d9, 0x00000321, 0x00000368,
	0x000003a1, 0x000003eb, 0x00000434, 0x00000448,
	0x00000470, 0x00000497, 0x000004ae, 0x000004e5,
	0x00000509, 0x0000052f, 0x0000055d, 0x00000581,
	// Entry 20 - 3F
	0x000005a7, 0x000005e1, 0x000005e7, 0x000005f1,
	0x000005fb, 0x00000602, 0x00000617, 0x0000062c,
	0x00000641, 0x00000647, 0x0000064f, 0x00000657,
	0x00000660, 0x00000671,
} // Size: 208 bytes

const enData string = "" + // Size: 1649 bytes
	"\x02unknown (built from source)\x02Boost your development workflow by at" +
	" least 10^12.\x02Display help information about the command\x02Display v" +
	"ersion information\x02Print version and exit\x04\x00\x01\x0a\x13\x02tera" +
	" version %[1]s\x02Run a job\x02Path to a configuration file. If left emp" +
	"ty, it will recursively search in the parent directories for a .tera.yml" +
	" file\x02Start the service management interface\x02An error occured calc" +
	"ulating an absolute path: %[1]s\x02An error occured when checking the pa" +
	"th \x22%[1]s\x22:\x0a%[2]s\x02The path \x22%[1]s\x22 is a directory\x02F" +
	"ailed to read the current working directory: %[1]s\x02No configuration f" +
	"ile could be found\x02The task #%[1]d has no command declared\x02No step" +
	" is declared in the job \x22%[1]s\x22\x02The step #%[1]d in the job \x22" +
	"%[2]s\x22 has no name declared\x02The step \x22%[1]s\x22 in the job \x22" +
	"%[2]s\x22 has invalid run_before hooks: %[3]s\x02The step \x22%[1]s\x22 " +
	"in the job \x22%[2]s\x22 has invalid run_after hooks: %[3]s\x02The step " +
	"\x22%[1]s\x22 in the job \x22%[2]s\x22 has no task declared\x02The task " +
	"\x22%[1]s\x22 in the step \x22%[2]s\x22 in the job \x22%[3]s\x22 is inva" +
	"lid: %[4]s\x02The task #%[1]d in the step \x22%[2]s\x22 in the job \x22%" +
	"[3]s\x22 is invalid: %[4]s\x02No name is declared\x02The run_before hook" +
	"s are invalid: %[1]s\x02The run_after hooks are invalid: %[1]s\x02No com" +
	"mand is declared\x02No job and no service is declared in the configurati" +
	"on\x02The key of a service is not defined\x02The service \x22%[1]s\x22 i" +
	"s invalid: %[2]s\x02The file could not be parsed from YAML: %[1]s\x02The" +
	" configuration is invalid: %[1]s\x02No valid configuration could be foun" +
	"d\x02The contents of the file \x22%[1]s\x22 could not be read: %[2]s\x02" +
	"ERROR\x02[command]\x02[--flags]\x02%[1]s:\x02Additional Commands:\x04" +
	"\x01 \x00\x10\x02(default %[1]s)\x04\x01 \x00\x10\x02(default %[1]q)\x02" +
	"USAGE\x02ALIASES\x02EXAMPLE\x02COMMANDS\x02ADDITIONNAL HELP"

var frIndex = []uint32{ // 46 elements
	// Entry 0 - 1F
	0x00000000, 0x0000002a, 0x00000072, 0x000000a9,
	0x000000cb, 0x000000ea, 0x00000102, 0x00000125,
	0x000001c0, 0x000001ea, 0x00000232, 0x00000281,
	0x000002aa, 0x000002e6, 0x0000031a, 0x0000033f,
	0x0000036e, 0x0000039b, 0x000003e5, 0x00000429,
	0x00000462, 0x000004ad, 0x000004f7, 0x00000511,
	0x00000539, 0x00000560, 0x00000581, 0x000005bc,
	0x000005d7, 0x000005ff, 0x0000062b, 0x00000655,
	// Entry 20 - 3F
	0x00000687, 0x000006c1, 0x000006c8, 0x000006d3,
	0x000006df, 0x000006e7, 0x000006f9, 0x00000712,
	0x0000072b, 0x00000731, 0x00000737, 0x0000073f,
	0x00000749, 0x0000075e,
} // Size: 208 bytes

const frData string = "" + // Size: 1886 bytes
	"\x02inconnue (compilation depuis les sources)\x02Démultipliez votre envi" +
	"ronnement de développement par au moins 10^12.\x02Afficher l'information" +
	" d'aide à propos de la commande\x02Afficher l'information de version\x02" +
	"Afficher la version et quitter\x04\x00\x01\x0a\x13\x02tera version %[1]s" +
	"\x02Exécuter une séquence de tâches\x02Chemin vers un fichier de configu" +
	"ration. Si aucune valeur n'est saisie, une recherche dans les dossiers p" +
	"arents pour un fichier .tera.yml sera exécutée.\x02Lancer l'interface de" +
	" gestion de services\x02Une erreur est survenue à la récupération d'un c" +
	"hemin absolu : %[1]s\x02Une erreur est survenue en listant les propriété" +
	"s du fichier \x22%[1]s\x22 :\x0a%[2]s\x02Le chemin \x22%[1]s\x22 pointe " +
	"vers un dossier\x02Impossible de lire le répertoire de travail actuel : " +
	"%[1]s\x02Aucun fichier de configuration n'a pu être trouvé\x02La tâche #" +
	"%[1]d n'a pas de commande\x02Aucun step n'est déclaré dans le job \x22%[" +
	"1]s\x22\x02Le step #%[1]d du job \x22%[2]s\x22 n'a pas de nom\x02Le step" +
	" \x22%[1]s\x22 dans le job \x22%[2]s\x22 a un hook run_before invalide :" +
	" %[3]s\x02Le step \x22%[1]s\x22 du job \x22%[2]s\x22 a un hook run_after" +
	" invalide : %[3]s\x02Le step \x22%[1]s\x22 du job \x22%[2]s\x22 ne conti" +
	"ent aucune tâche\x02La tâche \x22%[1]s\x22 dans le step \x22%[2]s\x22 du" +
	" job \x22%[3]s\x22 est invalide : %[4]s\x02La tâche #%[1]d dans le step " +
	"\x22%[2]s\x22 du job \x22%[3]s\x22 est invalide : %[4]s\x02Aucun nom n'e" +
	"st déclaré\x02Le hook run_before est invalide : %[1]s\x02Le hook run_aft" +
	"er est invalide : %[1]s\x02Aucune commande n'est déclarée\x02Aucun job o" +
	"u service n'est déclaré dans la configuration\x02Un service n'a pas de c" +
	"lé\x02Le service \x22%[1]s\x22 est invalide : %[2]s\x02Le fichier YAML n" +
	"'a pas pu être lu : %[1]s\x02La configuration n'est pas valide : %[1]s" +
	"\x02Aucune configuration valide n'a pu être trouvée\x02Le contenu du fic" +
	"hier \x22%[1]s\x22 n'a pas pu être lu : %[2]s\x02ERREUR\x02[commande]" +
	"\x02[--options]\x02%[1]s :\x02Autres commandes:\x04\x01 \x00\x14\x02(%[1" +
	"]s par défaut)\x04\x01 \x00\x14\x02(%[1]q par défaut)\x02USAGE\x02ALIAS" +
	"\x02EXAMPLE\x02COMMANDES\x02AIDE SUPPLÉMENTAIRE"

	// Total table size 3951 bytes (3KiB); checksum: 1BF2E99
